apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-n
  # these labels belongs to replicaset resource
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to ypur case
  replicas: 3
  selector:
    matchLabels: 
      tier: frontend
      app: nginx 
  # below is called pod definition
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
        project: some-project
    spec:
      containers:
      - name: nginx

