kind: Deployment
apiVersion: apps/v1
metadata: 
  name: nginx
  # these three labels are deployment related labels
  labels:
    app: nginx
    purpose: deployment
    tier: web
  spec: 
    replicas: 3
    selector: 
      matchLabels:
        app: nginx 
        tier: web
        project: test-project
    # pod definition
    template:
      metadata:
        labls:
          app: nginx
          tier: web
          project: test-project
          extra-key: extra-value
      spec:
        containers:
        - name: nginx
          image: nginx
